### ISSUE TITLE
PHP tests failing

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dep-server#133]
I noticed that PHP version line 8.1 wasn't present in the dep-server, so I took a look at the associated `test-and-upload` worklows. Every 8.1 version is failing during the test suite on this workflow like [in this example](https://github.com/paketo-buildpacks/dep-server/runs/4898970425?check_suite_focus=true). 

The error is:
```
/dependency-tests/php/run: line 28: /dependency-tests/php/fixtures/8-1/extensions.json: No such file or directory
``` 
on the `Test` step.

In order to eventually support this version line in the buildpack, we should look into why the test is failing, and fix it.

**Comment by brayanhenao** [comment]
C.C @arjun024

**Comment by arjun024** [comment]
Isn't that because there are no fixtures added to your tests for 8.1? https://github.com/paketo-buildpacks/dep-server/tree/main/actions/test-dependency/dependency-tests/php/fixtures

**Comment by sophiewigmore** [comment]
@arjun024 haha!! that could very much be it! I didn't investigate at all, just wanted to document it as I saw the issue in passing.

**Comment by arjun024** [comment]
@sophiewigmore Expect for your own tests, I don't think you need to do anything more. You should be able to use that builder to build php 8.1. The logic switching for 8.1 is taken care of [here](https://github.com/cloudfoundry/buildpacks-ci/blob/384c051f48fdb4b40521daaacc6afaab87da3796/tasks/build-binary-new/builder.rb#L893-L895)
