### ISSUE TITLE
Can the dependencies include license information?

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dep-server#21]
## What happened?

* What were you attempting to do?
I'd like to be able to see what licenses the dependencies have so that I can include that information in our buildpack metadata.

* What did you expect to happen?
When I query the API, I expect to see dependency information alongside the other dependency information.

    ```json
    [
      {
        "licenses": [
          {
            "type": "MIT",
            "uri": "https://github.com/krallin/tini/blob/v0.19.0/LICENSE"
          }
        ],
        "name": "tini",
        "version": "v0.19.0",
        "sha256": "81c7dd906dff4a9e69cae4c1eb959c2b3b4965b4df8e03594c8eea8f816bf1ee",
        "uri": "https://deps.paketo.io/tini/tini_v0.19.0_linux_noarch_bionic_81c7dd90.tgz",
        "stacks": [
          {
            "id": "io.buildpacks.stacks.bionic"
          }
        ],
        "source": "https://github.com/krallin/tini/tarball/v0.19.0",
        "source_sha256": "1e83f58ef41e7eac8e1d645bf16f3829ee4f3556dd1dd188eb14a09658cc7679",
        "deprecation_date": ""
      }
    ]
    ```

The `type` here is chosen from the list of [SPDX license identifiers](https://spdx.org/licenses/), and the `uri` is a link to the license referenced for the version of the dependency specified.

* What was the actual behavior? Please provide log output, if possible.
Instead, the response from the server does not include any license information.

    ```json
    [
      {
        "name": "tini",
        "version": "v0.19.0",
        "sha256": "81c7dd906dff4a9e69cae4c1eb959c2b3b4965b4df8e03594c8eea8f816bf1ee",
        "uri": "https://deps.paketo.io/tini/tini_v0.19.0_linux_noarch_bionic_81c7dd90.tgz",
        "stacks": [
          {
            "id": "io.buildpacks.stacks.bionic"
          }
        ],
        "source": "https://github.com/krallin/tini/tarball/v0.19.0",
        "source_sha256": "1e83f58ef41e7eac8e1d645bf16f3829ee4f3556dd1dd188eb14a09658cc7679",
        "deprecation_date": ""
      }
    ]
    ```

**Comment by martyspiewak** [comment]
I think this makes a lot of sense, but I am a bit concerned about the extent to which we will have to hard-code some of this data. For example, the `uri` for tini (`https://github.com/krallin/tini/blob/v0.19.0/LICENSE`) can be generated dynamically based on the version, but we will likely have to hard-code the `type` to `MIT` so if that ever changes we'd have to update what we've hard-coded.

The same would be true for something like Go where the license lives at `https://golang.org/LICENSE` and we'd have to hard-code the type to be BSD.

This might be fine and expected, but just wanted to call out these concerns and see if I'm understanding correctly.

**Comment by ryanmoran** [comment]
Could we try using something like https://github.com/go-enry/go-license-detector to detect the license SPDX for us?

**Comment by martyspiewak** [comment]
That's interesting. Yea I think that will work for most dependencies. There are a few that we'll probably still need to hard-code (like icu- the license is [here](http://www.unicode.org/copyright.html#License) and the [github repo](https://github.com/unicode-org/icu) has no license) but I think it's fine if there are a few exceptions that need to be hard-coded.

**Comment by ForestEckhardt** [comment]
Is there merit in having partial license information? So only providing license data for the dependencies that we can automatically detect license information and leave things that we cannot determine blank. That we were a centralizing as much data as possible but we aren't providing bad information through hard-coded values that have the possibility(I'll be it a slight one) of changing.

To me it feels like we should be as information rich as we can be while still be highly confident in the accuracy of our data, but those are just my 2 cents.

**Comment by ForestEckhardt** [comment]
This looks for the most part doable with a relatively high level of accuracy using https://github.com/go-enry/go-license-detector. We are planning on implementing the first iteration of this functionality, you can track our progress in [this issue](https://github.com/paketo-buildpacks/dep-server/issues/37). If you have anything that you feel needs to be added feel free to comment on that linked issue.
