### ISSUE TITLE
Clean up workflows

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dep-server#257]
At the end of https://github.com/paketo-buildpacks/rfcs/issues/236, we should go through the dep-server workflows and disable/remove anything we no longer need. For each dependency listed in the original issue, this will likely include:
- Workflows to getting new versions, building, and testing dependencies
- Removing the dependency from the [dependencies.yml file](https://github.com/paketo-buildpacks/dep-server/blob/main/.github/data/dependencies.yml)

Dependency List:
- [x] bundler
- [x] composer 
- [x] curl 
- [x] dotnet-aspnetcore 
- [x] dotnet-runtime
- [x] dotnet-sdk 
- [x] go
- [x] httpd 
- [x] icu 
- [x] nginx 
- [x] node 
- [x] php 
- [x] pip 
- [x] pipenv 
- [x] python
- [x] poetry 
- [x] ruby 
- [x] rust 
- [x] tini 
- [x] yarn 

This should result in dependency-specific workflows being removed from the dep-server. The workflow to deploy and run the dep-server should remain in-tact, as well as the legacy dependencies that are hosted in the dep-server in order to support old buildpack versions that reference those dependencies. We should also leave the dependency-specific code inside of [pkg/dependency](https://github.com/paketo-buildpacks/dep-server/tree/main/pkg/dependency) as-is, for future reference.

**Comment by ForestEckhardt** [comment]
All of the .NET dependencies must remain until `dotnet-core-runtime` and `dotnet-core-aspnet` are retired.

**Comment by ForestEckhardt** [comment]
Take a look at https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/issues/47 for a proposal on how to deprecate the `dotnet-core-runtime` and `dotnet-core-aspnet` buildpacks.

**Comment by sophiewigmore** [comment]
🥳 @ForestEckhardt
