### ISSUE TITLE
Add missing dependency versions in use by buildpacks

### ISSUE THREAD

**Issue by martyspiewak** [paketo-buildpacks/dep-server#26]
## What happened?
In order for the buildpacks to start consuming dependencies from the dep server, the dep server needs to have every version in use by the buildpacks. There are a few versions that are missing right now:

- [x] bundler 1.17.3
- [x] httpd 2.4.43
- [x] nginx 1.18.0
- [x] python 3.6.12
- [x] python 3.7.10
- [x] ruby 2.5.8
- [x] ruby 2.6.6
- ~~tini 0.19.0~~
- [x] yarn 1.22.4

These will need to be added before we can start work on [this issue](https://github.com/paketo-buildpacks/packit/issues/140).

**Comment by sophiewigmore** [comment]
@martyspiewak It look line tini already exists in the dep-server. Can you confirm for us that we're all good there?

**Comment by martyspiewak** [comment]
@sophiewigmore yup you're right, that was my bad. Sorry about that!

**Comment by sophiewigmore** [comment]
Done in dep-server for each listed dep.
