### ISSUE TITLE
Stop publishing the CAAPM dependency

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dep-server#48]
Following discussion in [this PHP issue](https://github.com/cloudfoundry/php-buildpack/issues/517), it appears that Bintray (where we pull the CAAPM dependency from) has been shut down. As a result, when we reach out to https://ca.bintray.com/apm-agents/CA-APM-PHPAgent-20.11.0_linux.tar.gz, the source URL in the [dep-server](https://api.deps.paketo.io/v1/dependency?name=caapm), we receive a `403 Forbidden` error.

As a result, the acceptance tests in this repo fail since that URL cannot be hit to get versions.

While it appears that there may be other locations to download/install CAAPM from, I don't believe we use it in the V3 PHP buildpacks which is where we'd want this dependency. 

For those reasons, I believe we should remove support for the CAAPM dependency from the dep-server all together. @dmikusa-pivotal / @paketo-buildpacks/php-maintainers does this seem reasonable to you?

**Comment by dmikusa-pivotal** [comment]
Seems reasonable. I do not believe we have anything in the v3 buildpack using it either.
