### ISSUE TITLE
Go dependencies should have SemVer versions

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dep-server#53]
## Summary
The current version numbers for the `go` dependencies report with the following format: `go1.15.3`. This breaks downstream version parsing logic that expects a SemVer version number. We should rewrite all of the versions we provide so that they conform to the SemVer format.

### Switch to JSON feed?
In the process of investigating this issue, I found that we are using a [regex on some HTML](https://github.com/paketo-buildpacks/dep-server/blob/3a991faef0ebe003533c80444eadb0a8232048dd/pkg/dependency/go.go#L161-L166) to find the versions of Go that are available. This type of scraping is really brittle and prone to break if that HTML changes. The Go team provides a JSON feed of the releases: https://golang.org/dl/?mode=json. Can we switch to using this feed to find versions of Go?

**Comment by sophiewigmore** [comment]
+1 to using the Go JSON feed 100%. These types of feeds were definitely what the team who put the dep-server together were looking to use, but it might not have been available at that point.

In terms of switching to SemVer, I don't care a huge amount but if we do switch we should make this change across the board for any other dependencies that might be in a different format.

**Comment by ForestEckhardt** [comment]
> In terms of switching to SemVer, I don't care a huge amount but if we do switch we should make this change across the board for any other dependencies that might be in a different format.

Agreed! We should sanitize our version information to be as SemVer-ic as possible to make it more accessible to other using the server or to those trying to build their own mirrors. I think we should potentially even make it required for consistency sake but I am not willing to die on the hill.

**Comment by sophiewigmore** [comment]
@ryanmoran @ForestEckhardt do you think it would be better if the version returned directly by the dependency-specific package lookup code should be SemVer compliant? 
Or would it be preferable to do the conversion during the build-upload workflow that gathers all of the metadata for publishing?

The benefits of the first option would be that the dependency-specific code would live directly with the rest of the other dependency-specific code in pkg/dependency/<dependency>.go

The benefit of the second option would be that we only have to add the conversion in one place, but it would be kind of a separate pattern from the rest of our code.

**Comment by robdimsdale** [comment]
It looks like this issue can be closed as all of the versions of golang have a semver-compatible `version` field:

```
❯ curl -s 'https://api.deps.paketo.io/v1/dependency?name=go' | jq .[].version
"1.17.10"
"1.18.2"
"1.18.1"
"1.17.9"
"1.18.0"
"1.17.8"
"1.16.15"
"1.17.7"
"1.16.14"
"1.17.6"
"1.16.13"
"1.17.5"
"1.16.12"
"1.17.4"
"1.16.11"
"1.17.3"
"1.16.10"
"1.17.2"
"1.16.9"
"1.17.1"
"1.16.8"
"1.16.6"
"1.16.5"
"1.16.7"
"1.16.1"
"1.16.4"
"1.15.14"
"1.15.11"
"1.15.10"
"1.15.15"
"1.15.9"
"1.17.0"
"1.15.12"
"1.16.3"
"1.16.2"
"1.15.13"
"1.16.0"
```
