### ISSUE TITLE
Update workflows and actions to create and upload pURL field for dependencies

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/dep-server#84]
# Background
Based on the conclusion from the investigation which can be seen in #42 , all buildpack dependencies should have a pURL as part of their metadata on the dep-server.

# Implementation
- [x] Update action to generate a pURL for all of the dependencies currently served by the dep-server
- [x] Update the workflows to include this metadata as part of the upload
- [x] Backfill all of the existing dependency entries with pURLs
  - [x] bundler
  - [x] composer
  - [x] curl
  - [x] dotnet-aspnetcore
  - [x] dotnet-runtime
  - [x] dotnet-sdk
  - [x] go
  - [x] httpd
  - [x] icu
  - [x] nginx
  - [x] node
  - [x] php
  - [x] pip
  - [x] pipenv
  - [x] python
  - [x] ruby
  - [x] rust
  - [x] tini
  - [x] yarn
# Acceptance
This story is complete when the following conditions are met.
1. A pURL is generated for ~~all dependencies by an action~~  each dependency when it is built during the `build-upload` workflow.
1. The ~~existing~~ `test-upload` workflow upload the pURL to the dep-server successfully
1. All of the dependencies/versions of each currently served by the dep-server have pURLs in their metadata  when we go to the dep-server url.

**Comment by ForestEckhardt** [comment]
Blocked on #83

**Comment by sophiewigmore** [comment]
Unblocked on #83 now it has been completed

**Comment by sophiewigmore** [comment]
Done in #89: Update action to generate a pURL for all of the dependencies currently served by the dep-server
Done in #89: Update the workflows to include this metadata as part of the upload

**Comment by sophiewigmore** [comment]
TODO:
fix up icu, and make sure all dependencies have well-formed purls.
