### ISSUE TITLE
Do we need to support PHP 7.2.*?

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dep-server#86]
When implementing #54, the [`test-upload` workflow ](https://github.com/paketo-buildpacks/dep-server/runs/3080319965?check_suite_focus=true) for PHP version 7.2.34 failed on the tests that we run on our compiled artifact. When deciding whether to investigate this error, I realized that version line 7.2 is no longer supported upstream and is not supported in our buildpacks as of [PHP Dist Buildpack v0.1.0](https://github.com/paketo-buildpacks/php-dist/releases/tag/v0.1.0).

Given this context, do we need to support this version line in the dep-server? Due to the labor intensive compilation process (with extensions) and the status of the version line I don't believe we need to.

I am looking to @paketo-buildpacks/php-maintainers and @brayanhenao (Dependency Maintainer) to weigh in here.

The outcomes of this issue should either be:
A. Remove the version line from the dep-server all together, OR
B. Keep the version line, and investigate the test failures in https://github.com/paketo-buildpacks/dep-server/runs/3080319965?check_suite_focus=true.

**Comment by arjun024** [comment]
PHP 7.2 is beyond End of Life and does not even get critical patches. https://www.php.net/supported-versions.php
We do not have to support that version line anymore.

**Comment by sophiewigmore** [comment]
This version has been removed!
